In [2]:
import numpy as np

In [3]:
#list to array
lst = [1, 2, 3]
arr = np.array(lst)
print(arr,"\n")


[1 2 3] 



In [4]:
#array of a range
print(np.arange(0,10), "\n")
print(np.arange(0,10,2), "\n")


[0 1 2 3 4 5 6 7 8 9] 

[0 2 4 6 8] 



In [5]:
#array of any number, "zeros can be replaced by ones, twos....."
print(np.zeros(5), "\n")
print(np.zeros((2,5)), "\n")


[0. 0. 0. 0. 0.] 

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 



In [6]:
#linspace to get array evenly spaced arrays between 2 numbers
print(np.linspace(2,10,4), "\n")


[ 2.          4.66666667  7.33333333 10.        ] 



In [7]:
#identity matrix using eye()
print(np.eye(5), "\n")


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 



In [21]:
#to get a random integer, (inclusive, exclusive, number of ints)
rarr = np.random.randint(1,50, 25)
print(rarr)
newrarr = rarr.reshape(5,5)
newrarr


[46 25 23  9  4  1 35 47  7 18 32 18 39 49 18 49 45 36 36 35 12 10 31 14
 41]


array([[46, 25, 23,  9,  4],
       [ 1, 35, 47,  7, 18],
       [32, 18, 39, 49, 18],
       [49, 45, 36, 36, 35],
       [12, 10, 31, 14, 41]])

In [12]:
#useful functions
print("max: ", rarr.max(), "   max index: ", rarr.argmax(), "\n", "min: ", rarr.min(), "  min index: ", rarr.argmin())

max:  49    max index:  12 
 min:  9   min index:  10


In [13]:
rarr[:4]

array([11, 13, 13, 34])

In [16]:
#in numpy, a slice of an array is not a copy, it's a view of the original array, so any changes in the sliced array will be applied in the og array too
narr = np.random.randint(0,100,10)
slicearr = narr[0:3]
slicearr[:] = 8
print("sliced array: ", slicearr, "\n", "original array: ", narr)

#to make a copy of an array use copy()
narr_c = narr.copy()
narr_c[:] = 11
print("copied array: ", narr_c, "\n", "original array: ", narr)


sliced array:  [8 8 8] 
 original array:  [ 8  8  8 80 58 54 98 50 81 73]
copied array:  [11 11 11 11 11 11 11 11 11 11] 
 original array:  [ 8  8  8 80 58 54 98 50 81 73]


In [25]:
#grabbing elements from 2d array
print(newrarr)
print(newrarr[0][2])
print(newrarr[0,2])
print(newrarr[:3,2:])

[[46 25 23  9  4]
 [ 1 35 47  7 18]
 [32 18 39 49 18]
 [49 45 36 36 35]
 [12 10 31 14 41]]
23
23
[[23  9  4]
 [47  7 18]
 [39 49 18]]


In [29]:
#checking if elements pass a condition, next is to pass the condition itself in the array [] in order to get those elements which pass the condition
print(rarr > 25)
print(rarr[rarr > 25])

[ True False False False False False  True  True False False  True False
  True  True False  True  True  True  True  True False False  True False
  True]
[46 35 47 32 39 49 49 45 36 36 35 31 41]


In [37]:
#array operations(+,-,*,/, **(exponent), sqrt())
print(rarr + rarr)
print(rarr - rarr)
print(rarr * rarr)
print(rarr / rarr)
print(rarr ** 2)
print(rarr.sqrt())

[92 50 46 18  8  2 70 94 14 36 64 36 78 98 36 98 90 72 72 70 24 20 62 28
 82]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[2116  625  529   81   16    1 1225 2209   49  324 1024  324 1521 2401
  324 2401 2025 1296 1296 1225  144  100  961  196 1681]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1.]
[2116  625  529   81   16    1 1225 2209   49  324 1024  324 1521 2401
  324 2401 2025 1296 1296 1225  144  100  961  196 1681]


In [35]:
#changing every element by some operation(+, -, *, /, **(exponent), sqrt(), sin(), log())
print(rarr)
print(rarr + 100)


[46 25 23  9  4  1 35 47  7 18 32 18 39 49 18 49 45 36 36 35 12 10 31 14
 41]
[146 125 123 109 104 101 135 147 107 118 132 118 139 149 118 149 145 136
 136 135 112 110 131 114 141]


In [36]:
#in python /0 is an error but numpy will give a warning and still give an output
print(rarr/0)

[inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf
 inf inf inf inf inf inf inf]


<ipython-input-36-00a6d39c5956>:2: RuntimeWarning: divide by zero encountered in true_divide
  print(rarr/0)
